const term = {
  "single": {
    "AAES": "自适应电台",
    "AC": "交流电",
    "ADD": "增加",
    "ADP": "全程预告",
    "AFTER": "以后",
    "AGN": "再，再来一次",
    "AHR": "另外的",
    "ALL": "完全，全部",
    "ALSO": "也，同样",
    "ALY": "经常",
    "AMP": "调幅话",
    "ANS": "回答",
    "ANT": "天线",
    "ASK": "问",
    "AT": "在",
    "AT ONCE": "立即",
    "AUTO": "自动发报机",
    "BAD": "坏，不好",
    "BC": "广播",
    "BD": "波特",
    "BEC": "因为",
    "BGN": "开始",
    "BK": "单工插入法",
    "BOZ": "双方",
    "BR": "双路",
    "BS": "盲发",
    "BTR": "较好",
    "BUT": "但是",
    "BY": "被",
    "BY ORDER": "奉命",
    "C": "份",
    "CAN": "能够",
    "CANT": "不能",
    "CCK": "通信检查",
    "CCD": "集中控制台",
    "CH": "中文",
    "CHAN": "信道",
    "CHG": "换",
    "CHIEF": "领班",
    "CK": "组数(字数)",
    "CL": "呼叫",
    "CLR": "清楚",
    "CLS": "等级",
    "CODE": "代密，密语",
    "CODEK": "数码键",
    "COMM": "联络",
    "CQ": "通播",
    "COMP": "计算机",
    "CRT": "更正",
    "CS": "呼号",
    "CTGL": "遥控线",
    "CTRB": "控制盒",
    "CW": "等幅报",
    "CURRENT": "电流",
    "CUT OFF": "中断",
    "CY": "抄，抄收",
    "DAILY": "每日",
    "DASH": "划",
    "DATE": "日期",
    "DC": "直流电",
    "DEL": "递送",
    "DELY": "延误，耽搁",
    "DETEET": "探测",
    "DOTS": "点子",
    "DMSG": "数据报",
    "DUTY": "值班，值班台",
    "DX": "双工",
    "EFES": "扩频电台",
    "EK": "电子键",
    "END": "末尾，完了",
    "ENG": "英文",
    "ES": "和，与，以及",
    "ERR": "错误",
    "EX": "练习",
    "FAST": "快",
    "FAX": "传真机",
    "FFY": "定频",
    "FIG": "码，数码",
    "FIL": "经有线电路传递",
    "FM": "从，从前一组",
    "FMS": "测频台",
    "FMSG": "快速报",
    "FSK": "移频手键报",
    "FORGET": "忘记",
    "FREQ": "频率",
    "FWD": "发出",
    "G": "批",
    "GA": "发下来",
    "GARBLED": "迭码",
    "GB": "再会",
    "GD": "好、好的",
    "HARD": "困难",
    "HD": "手",
    "HFES": "跳频电台",
    "HR": "这里",
    "HRD": "听到",
    "HV": "有、已经",
    "HVO": "用半压工作",
    "HW": "怎样、如何",
    "I": "我",
    "IEC": "识别暗令",
    "IF": "如果",
    "INV": "无效",
    "IS": "是",
    "JM": "连码",
    "JUST": "刚才",
    "K": "请回答",
    "KC": "千周",
    "KEY": "电键",
    "KP": "守听",
    "KRZ": "某台正叫你",
    "LF": "换行",
    "LG": "长（低）",
    "LGR": "长（低）一点",
    "LL": "有线",
    "LTR": "字码",
    "LW": "长波（夜频）",
    "LWSB": "下边带（表示路数在其后发1或者2）",
    "M": "分钟",
    "MANY": "多、许多",
    "MASTER": "台长、队长",
    "MC": "兆周",
    "MCW": "调幅报",
    "MFCT": "多功能通信终端",
    "MNR": "单路",
    "MODEM": "市制解调器",
    "MOTOR": "马达",
    "MSG": "电报",
    "MSGS": "多份电报",
    "MUTI": "变字",
    "NEW": "新",
    "NEXT": "下次",
    "NIL": "无事、没有什么",
    "NO": "不、不对、不同意",
    "NOT": "没有",
    "NOTE": "注意",
    "NR": "号数",
    "NW": "现在",
    "OBS": "天气电报",
    "OHV": "关高压",
    "OK": "对了、同意",
    "OFF": "关、断开",
    "OLD": "老、原来的",
    "ON KEY": "上机",
    "ONLY": "只有、仅仅",
    "OPR": "报务员",
    "OR": "或者",
    "OWCOMM": "单向通信",
    "P": "页",
    "PAR": "参数",
    "PBL": "报头",
    "PHONE": "用话工作",
    "PPR": "纸",
    "PSE": "请",
    "PTR": "电传机",
    "PUNCH": "凿孔",
    "PWR": "电源",
    "QRH": "波长（频率）",
    "QRJ": "信号小",
    "QRL": "工作忙",
    "QRM": "他台干扰",
    "QRN": "天电干扰",
    "QRO": "增加电力",
    "QRP": "减低电力",
    "QRQ": "发快些",
    "QRS": "发慢些",
    "QRT": "停止发信",
    "QRU?": "你有报吗？",
    "QRW": "转告",
    "QRX": "请等待××分钟",
    "QRY": "请按下列次序发报",
    "QSA?": "本台信号强度如何",
    "QSA1": "信号很小不能工作",
    "QSA2": "信号小工作困难",
    "QSA3": "信号可以",
    "QSA4": "信号好",
    "QSA5": "信号很好",
    "QSB": "信号不稳",
    "QSD": "手法不清楚",
    "QSK": "约会时间",
    "QSL?": "请给收据",
    "QSL": "给你收据",
    "QSO": "直接联络",
    "QSP": "转报",
    "QSY": "改变波长（改变频率）",
    "QSZ": "每组发两遍",
    "QTA": "取消",
    "QTB": "查对组数",
    "QTR?": "现在是什么时间",
    "QTR": "现在的时间是×××",
    "R": "听到了、对",
    "RATE": "码率",
    "RANGE": "范围",
    "RCVR": "收信机",
    "RDO": "无线电",
    "RECD": "已收到",
    "RETRANS": "重译",
    "RIBBON": "色带",
    "RMKS": "附注",
    "RNR": "流水号数",
    "RPRG": "修理",
    "RPT": "重复",
    "RPY": "回电",
    "SCAN": "扫描",
    "SD": "发、发报",
    "SEE": "看",
    "SHT": "短（高）",
    "SHTR": "短（高）一点",
    "SIG": "信号",
    "SLIP": "纸条",
    "SOC": "报底上如此",
    "SOS": "国际遇险（求救）信号",
    "SPC": "间隔",
    "STN": "电台",
    "STNFM": "发报台",
    "STNTO": "收报台",
    "STP": "停止",
    "SRY": "对不起",
    "SW": "短波（日频）",
    "SWT": "转信",
    "SX": "单工",
    "SSB": "单边带",
    "SSBP": "单边带话",
    "SVC": "公电",
    "TC": "校对",
    "TELL": "告诉",
    "TIME": "时间",
    "TKS": "谢谢",
    "TMW": "明天",
    "TO": "到",
    "TOLLSTN": "机务站",
    "TPCY": "旁抄",
    "TPO": "传真",
    "TRANS": "翻译",
    "TRUB": "故障",
    "TRY": "试，试验",
    "TUNE": "调整",
    "TY": "今天",
    "TXT": "电文",
    "U": "你，你们",
    "UGT": "紧急",
    "UNTRANS": "译不出",
    "UPSB": "上边带",
    "USE": "用",
    "VIA": "经，经过",
    "VY": "很",
    "W": "组，字",
    "WK": "工作",
    "XLTR": "译电员",
    "XMTR": "发信机",
    "XQS": "请原谅",
    "XXX": "警报信号",
    "YES": "是的",
    "YR": "你的，你们的",
    "YY": "昨天",
    "ZAN": "听不到",
    "ZCF": "频率不准，请校正",
    "ZDM": "漏点",
    "ZFO": "信号衰落",
    "ZLD": "电键、继电器短路",
    "ZNN": "无报",
    "ZNR": "没收到",
    "ZPF": "电传机马达快了",
    "ZPS": "电传机马达慢了",
    "ZRA": "纸条放反了",
    "ZSK": "自动收信系统",
    "ZTH": "用手键发报",
    "ZVC": "电传机变字",
    "ZWC": "杂音干扰",
    "ZWO": "每组发一遍"
  },
  "frase": {
    "QRU? K": "你有报吗?请回答",
    "R ZNN SK": "听到了无报结束联络",
    "HR ZNN SK": "这里无报结束联络",
    "R SK": "听到了结束联络",
    "MSG": "电报",
    "MSG HW": "电报怎样",
    "HR MSG PSE CY HW?": "这里电报请抄怎样?",
    "HR RCVR TRUB NW BS PSE NOTE CY": "这里收信机故障现在盲发请注意抄",
    "GA": "发下来",
    "TRY GA": "试发下来",
    "YR MSG TRY GA": "你的电报试发下来",
    "ALL GA": "全部发下来",
    "YR MSG QRX HR MSG 11 PSE CY": "你的电报请等这里有较急电报请抄",
    "ZNN QRU?": "无报你有报吗?",
    "MSG PSE CY": "电报请抄",
    "RPT PBL": "重复报头",
    "NR1 CK85 56 1018 1413": "1号85组等级5610月18日14点13分",
    "RPT DATE TIME": "重复日期时间",
    "DATE 1018 TIME 1413": "日期10月18日时间14点13分",
    "RPT CLS": "重复等级",
    "CLS IS 56": "等级是56",
    "CLS 56": "等级56",
    "RPT NR1 38W NR2 SD AGN": "重复1号报38组2号重发",
    "RPT 12W 69W TO 78W 2P GA": "重复12组69组到78组第2页发下来",
    "YR NR6 CK?": "你的6号报组数是多少?",
    "YR MSG CK38 NR?": "你的报组数38号数是多少?",
    "YR NR4 2P MANY 10W PSE NOTE SD": "你的4号报2页多10组请注意发",
    "CK 58 OK?": "组数58对吗?",
    "NO CK 59 HR QTB 10W": "不对组数59这里查对组数10组",
    "HR NR3 PSE TC 15W TO 35W": "这里3号报请校对15组到35组",
    "R HR TC 15W FM": "听到了这里校对从15组",
    "23W IS 5164 PSE CRT": "23组是5164请更正",
    "YR NR7 HR ALL TC PSE NOTE SEE": "你的7号报这里全部校对请注意看",
    "HR NR8 CLS IS 46 PSE CRT": "这里8号报等级是46请更正",
    "HR NR1 QSL?": "这里1号报请给收据?",
    "YR NR1 QSL": "你的1号报给你收据",
    "BEC JUST HR AC STP PSE SD AGN": "因为刚才这里停电请重发",
    "HR NR3 TO NR6 QSL?": "这里3号到6号报请给收据?",
    "YR NR3 TO NR6 ALL QSL?": "你的3号到6号报全过程请给收据?",
    "YR NR3 NR4 NR6 QSL RPT NR5 41W": "你的3号4号6号报给你收据重复5号报第41组",
    "HR MSG NR9 AT 0830 SD TO U QSL?": "这里9号报在8点30分发到你的请给收据?",
    "YR NR9 ZNR PSE SD AGN": "你的9号报没收到请重发",
    "HR NR10 AT 1025 BS TO U CY OK?": "这里10号报在10点25分盲发到你抄对了吗?",
    "YR NR10 HR 1035 CY OK QSL": "你的10号报这里在10点35分抄对的给你收据",
    "YR NR5 YY 2350 RECD QSL": "你的5号报昨天二十三点五十分已收到给你收据",
    "HR CQ PSE ALL CY": "这里通播电报请都抄收",
    "XGO XGO HR R HR HV CQ AS XGB ANS": "XGOXGO听到你们了这里有通播电报请稍等XGB回答",
    "XGB ZNN SK XGO XGC MSG PSE CY": "XGB无报结束联络XGOXGC有报请抄",
    "AFTER 1400 TO 1600 HR SD CQ PSE NOTE KP": "以后14点到16点这里拍发通播电报请注意守听",
    "XGB HR CQ MSG NO TO U PSE QRX 30M": "XGB这里通播电报不到你请等30分钟",
    "HR MSG TO XGO PSE QSP HW?": "这里有报到XGO请转报怎样?",
    "XGO MSG TO U PSE CY HW?": "XGO电报到你请抄收怎样?",
    "HR TRY QSP GA": "这里试转请发下来",
    "HR NO COMM XGO CANT QSP PSE QSO": "这里不联络XGO不能转请直接联络",
    "U COMM XGO TIME?": "你联络XGO是什么时间?",
    "HR 0800 1500 2300 COMM XGO": "这里8点15点23点联络XGO",
    "HR MSG IS XGA TO YR PSE CY": "这里的电报是XGA到你的请抄",
    "RPT NR6 RMKS": "重复6号报的附注",
    "YR MSG NR6 XGO AT 1730 QSL": "你的6号报XGO在17点30分给你收据",
    "HR NR4 PSE QTA": "这里4号报请取消",
    "HR QSO NR4 QTA": "这里直接联络4号报请取消",
    "HR NR4 PSE U USE LL FAST QSP TO XGA": "这里4号报请你用有线快转到XGA",
    "HR COMM XGA CUT OFF MSG11 PSE QSP HW": "这里和XGA中断联络特急电报请转报如何?",
    "XGA HRD U QSA4 PSE BS": "XGA听你信号好请盲发",
    "STNTO IS XGD?": "收报台是XGD吗?",
    "NO STNTO IS XGB PSE CRT": "不对收报台是XGB请更正",
    "PSE QRW XGO AT 1500 COMM HR HW?": "请转告XGO在15点联络这里如何?",
    "HV MSGS TO XGO PSE QRW ATONCE COMM HR": "有多份电报到XGO请转告立即联络这里",
    "QRW XGO HR BY ORDER 1800 QRT": "转告XGO这时奉命18点停止发信",
    "YES HR QRW PSE NOTE KP": "是的这里转告请注意守听",
    "HR CANT QRW PSE QSO": "这里不能转告请直接联络",
    "PSE AT 1500 COMM XGA": "请在15点联络XGA",
    "XGA HV MSG TO U PSE ATONCE COMM": "XGA有报到你请立即联络",
    "XGB NW CL U PSE ATONCE KP": "XGB现在呼叫你请立即守听",
    "QRW XGO HR 1600 RPRG PWR 1800 COMM": "转告XGO这里16点修理电源18点联络",
    "XGO 1800 CANT COMM U 1700 HW": "XGO18点不能联络你17点怎样",
    "XGA QRH SHT PSE NOTE KP": "XGA的频率高请注意守听",
    "XGO XMTR TRUB CANT ANS YR SIG GD MSG PSE BS": "XGO发信机故障不能回答听你信号好电报请盲发",
    "XGO RCVE TRUB CANT COMM": "XGO收信机故障不能联络",
    "XGB FM 0600 TO 0700 ANS U INV PSE AFTER NOTE KP": "XGB从6点到7点回答你无效请以后注意守听",
    "XGC 2000 AC STP CANT USE XMTR IF U HV MSG PSE BS": "XGC20点停电不能使用发信机如果你有报请盲发",
    "QSA?": "本台信号强度如何?",
    "QSA4 YR MSG QRQ GA": "信号好你的报快些发下来",
    "QSA2 SE TUNE ": "信号小工作困难请调整",
    "QSA5 PSE AFTER SHT CL": "你的信号很好请以后短叫",
    "HR HV MSGS QSA?": "这里有多份电报信号强度如何?",
    "QSA5 YR MSG ALL GA": "信号很好你的电报全发下来",
    "QSA3 QRS GA": "信号可以慢些发下来",
    "QSA2 TUNE AGN TRY GA": "信号小工作困难请再调整试发下来",
    "QRJ TUNE OR QRO": "信号小调整或者增加电力",
    "QRJ VY PSE NOTE TUNE LG CL": "信号小得很请注意调整长呼叫",
    "QSB PSE NOTE MOTOR MSG TRY GA": "信号不稳请注意马达电报试发下来",
    "QSB PSE CHG XMTR HW?": "信号不稳请换发信机如何?",
    "QSB VY PSE NOTE ANT": "信号很不稳请注意天线",
    "YR XMTR ZDM PSE TUNE": "你的发信机漏点请调整",
    "HR CHG XMTR PSE NOTE KP": "这里换发信机请注意守听",
    "YR ZLD PSE NOTE": "你的电键(继电器)短路请注意",
    "QSA4 ZWO 2P GA": "信号好每组发一遍第二页发下来",
    "QRM LG CL MSG TRY GA": "他台干扰长叫电报试发下来",
    "QRM QRS GA": "他台干扰慢些发下来",
    "QRM QRN QSZ": "他台干扰天电干扰每组发两遍",
    "QRM PSE QSY LGR": "他台干扰请把频率改低一些",
    "QRM VY PSE QSY LG 80KC": "他台干扰很大请把频率改低80千周",
    "QRM QSY1": "他台干扰改1号备用频率",
    "QRM PSE QSY SHT VY": "他台干扰请把频率改很高",
    "QRN CANT CY QSY SW": "天电干扰不能抄改日频",
    "QRN USE LG FIG GA": "天电干扰用长码发下来",
    "QRM BC QSY OLD QRH LG CL": "广播电台干扰改加原来频率长叫",
    "ZAN PSE AT OLD QRH ANS": "听不到请在原来的频率回答",
    "PSE USE PHONE": "请用话工作",
    "QRN PSE MCW": "天电干扰请用调幅报工作",
    "PSE CW": "请用报工作",
    "HR QSY SHT VY PSE NOTE KP": "这里改很高请注意守听",
    "HR QSZ": "这里每组发两遍",
    "HR CHG NEW XMTR PSE KP": "这里换新发信机请守听",
    "QSD QRS": "手法不清发慢些",
    "QSD ZDM MSG SD AGN": "手法不清漏点电报重发",
    "U SD 6 ES 7 NO CLR PSE NOTE": "你发的6和7不清楚请注意",
    "U SD SPC BAD PSE QRS": "你发的间隔不好请发慢些",
    "QRL IF CANT QRQ PSE CHG CHIEF": "工作忙如果不能发快请换领班",
    "QSD PSE CHG OLD HD": "手法不清请换老手",
    "U SD JM PSE NOTE SPC": "你发的连码请注意间隔",
    "U SD DASH VY SHT CANT CY QRS": "你发的划很短不能抄请发慢",
    "U SD VY GD NR2 RPT 15W AHR ALL QSL": "你发的很好2号报重复15组另外的全给收据",
    "YES HR CHG OLD OPR AS": "是的这里换老报务员请稍等",
    "SRY HR IS NEW HD CANT QRQ XQS": "对不起这里是新手不能发快请原谅",
    "HR CHG MASTER ON KEY AS": "这里换台长上机请稍等",
    "QSK1800 HW?": "约会18点怎样?",
    "OK SK130": "同意结束联络",
    "QTR 1351": "现在时间是13点51分",
    "AFTER BOZ ADD COMM TIME 0500 1300 HW?": "以后双方增加联络时间5点13点怎样?",
    "HR 0500 1300 QRL 0900 1800 HW?": "这里5点13点工作忙9点18点怎样?",
    "0500 OK 1300 QRL 1500 HW?": "5点同意13点工作忙15点如何?",
    "YR NR15 HR UNTRANS PSE RETRANS": "你的15号报这里译不出请重译",
    "HR NR15 NO TO U PSE QTA": "这里15号报不到你请取消",
    "BOZ USE BK HW?": "双方使用单工插入法（双工）怎样?",
    "PSE USE SX": "请用单工",
    "NEXT BOZ AT LW COMM HW?": "下次双方在夜频联络怎样?",
    "BY ORDER TY 1200 BOZ USE NEW CS ES FREQ WK": "奉命今天12点双方用新呼号和频率工作",
    "YES SK": "是的结束联络",
    "PSE USE PTR WK HW?": "请用电传机工作怎样?",
    "HR CANT USE PTR": "这里不能用电传机",
    "BOZ AT 1000 USE LL WK HW?": "双方在十点用有线工作怎样?",
    "HR 1400 TO 1500 KP INV U COMM?": "这里14点到15点守听无效你联络了吗?",
    "HR 1405 HRD U BEC XMTR TRUB CANT ANS": "这里14点05分听到你因为发信机故障不能回答",
    "HR ANS INV": "这里回答无效",
    "1400 TO 1500 HR ALSO DP INV": "14点到15点这里也守听无效",
    "SRY HR FORGET COMM": "对不起这里忘记联络",
    "TMW 0600 HR TRY NEW XMTR PSE NOTE KP": "明天6点这里试新发信机请注意守听",
    "TELL YR MASTER TMW 0800 ON KEY WK": "告诉你们的台长明天8点上机工作",
    "HR MASTER NO AT ONLY CHIEF": "这里台长不在只有领班",
    "YR CODE NO PSE CK": "你的代密不对请检查"
  }
};

const keyCode = {
  "A": [0, 1],
  "B": [1, 0, 0, 0],
  "C": [1, 0, 1, 0],
  "D": [1, 0, 0],
  "E": [0],
  "F": [0, 0, 1, 0],
  "G": [1, 1, 0],
  "H": [0, 0, 0, 0],
  "I": [0, 0],
  "J": [0, 1, 1, 1],
  "K": [1, 0, 1],
  "L": [0, 1, 0, 0],
  "M": [1, 1],
  "N": [1, 0],
  "O": [1, 1, 1],
  "P": [0, 1, 1, 0],
  "Q": [1, 1, 0, 1],
  "R": [0, 1, 0],
  "S": [0, 0, 0],
  "T": [1],
  "U": [0, 0, 1],
  "V": [0, 0, 0, 1],
  "W": [0, 1, 1],
  "X": [1, 0, 0, 1],
  "Y": [1, 0, 1, 1],
  "Z": [1, 1, 0, 0],
  "0": [1, 1, 1, 1, 1],
  "1": [0, 1, 1, 1, 1],
  "2": [0, 0, 1, 1, 1],
  "3": [0, 0, 0, 1, 1],
  "4": [0, 0, 0, 0, 1],
  "5": [0, 0, 0, 0, 0],
  "6": [1, 0, 0, 0, 0],
  "7": [1, 1, 0, 0, 0],
  "8": [1, 1, 1, 0, 0],
  "9": [1, 1, 1, 1, 0],
  "?": [0, 0, 1, 1, 0, 0],
  "/": [1, 0, 0, 1, 0],
  "<": [1, 0, 1, 1, 0, 1],
  ">": [1, 0, 1, 1, 0, 1],
  "。": [0, 0, 2, 0, 0, 2, 0, 0],
  ".": [0, 1, 0, 1, 0, 1]
};

export {
  term, keyCode
}
